### ISSUE TITLE
Writing a single character clears the whole font

### ISSUE THREAD

**Issue by pawelsky** [FrSkyRC/PixelOSD#11]
When I try to read (`OSD_CMD_READ_FONT`) and then write (`OSD_CMD_WRITE_FONT`) a single `O` character (e.g. to modify its metadata) the whole font seems to be erased.

Attached picture shows text that has been written before `OSD_CMD_WRITE_FONT` is correctly displayed, but then the widgets that were drawn after the `OSD_CMD_WRITE_FONT` are not. The only character that is written correctly is the `O` character seen at the bottom (used as a char gauge) that was written with the `OSD_CMD_WRITE_FONT`
![image](https://user-images.githubusercontent.com/7121220/87873165-73fb3180-c9bf-11ea-91e0-2acf7f1033ae.png)

Here is the log from the simulator
```
[D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\font.c:68@0] Font storage size 32768K / 8 pages
[D:Z:\Source\FrSky\OSD\firmware\src\main\osd_output_config.c:39@140] found osd config at 0000000001916A90
[D:Z:\Source\FrSky\OSD\firmware\src\main\osd_output_config.c:39@143] found osd config at 0000000001916A98
set brightness = -1, horizontal offset = 0, vertical offset = 1
listening on serial port COM3
[D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\drawing.c:629@148] Clear screen
[D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\drawing.c:629@6254] Clear screen
[D:Z:\Source\FrSky\OSD\firmware\src\main\widgets\sidebar.c:244@6281] sidebar widget 0 configured in rect (10, 50) (75x150)
[D:Z:\Source\FrSky\OSD\firmware\src\main\widgets\sidebar.c:244@6307] sidebar widget 1 configured in rect (275, 50) (75x150)
[D:Z:\Source\FrSky\OSD\firmware\src\main\widgets\graph.c:672@6335] Graph 0 setup from (4, 52) to (176, 196) (172x144)
[D:Z:\Source\FrSky\OSD\firmware\src\main\osd_protocol.c:130@6363] Requesting font character 79
[D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\font.c:126@6367] Read font at addr 79
[D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\font.c:127@6368] 0x55 0x55 0x55 0x55 0x55 0x55 0x55 0x55 0x55
 [D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\font.c:127@6372] 0x55 0x55 0x55 0x55 0x00 0x15 0x54 0xaa
 [D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\font.c:127@6374] 0x85 0x52 0xaa 0xa1 0x52 0x80 0xa1 0x52
 [D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\font.c:127@6378] 0x84 0xa1 0x52 0x84 0xa1 0x52 0x84 0xa1
 [D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\font.c:127@6381] 0x52 0x84 0xa1 0x52 0x80 0xa1 0x52 0xaa
 [D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\font.c:127@6384] 0xa1 0x54 0xaa 0x85 0x55 0x00 0x15 0x55
 [D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\font.c:127@6386] 0x55 0x55 0x55 0x55 0x55 0x55 0x55 0x55
 [D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\font.c:127@6388] 0x55 0x55 0x55 0x55 0x55 0x55 0x55
 [D:Z:\Source\FrSky\OSD\firmware\src\main\flash_writer.c:14@6419] Flash unlocked, erasing range 01822850-0182a850
erase range 25307216-25339984
[D:Z:\Source\FrSky\OSD\firmware\src\main\flash_writer.c:53@11452] write finished, flash locked
```

I'm using windows simulator v1.0.1 but the same problem is observed on the OSD v2.0.0.

**Comment by fiam** [comment]
This is, unfortunately, a limitation of the hardware. We don't need to erase the whole font, but we'd need to at least erase the whole page that contains the character, and I felt that would be more confusing, specially if we eventually have a v2 hardware version that uses a bigger page size. By erasing the whole block, we ensure that no 3rd party code relies on the underlying hardware implementation details. The simulator just replicates the behaviour of the hardware device, so we can run automated tests without having to involve an instance of the real hardware.

However, I think we do need to document it properly. I'll update the docs to indicate that limitation.

**Comment by pawelsky** [comment]
It definitely needs to be documented as it may cause a lot of confusion.

Did you consider storing (temporarily in other place) the other character data and then restore it (except the newly written character), so that modifying a single character would be possible?
