### ISSUE TITLE
[DOCUMENTATION] Response returned by OSD_CMD_WIDGET_SET_CONFIG undocummented

### ISSUE THREAD

**Issue by pawelsky** [FrSkyRC/PixelOSD#12]
Documentation of the [OSD_CMD_WIDGET_SET_CONFIG command](https://github.com/FrSkyRC/PixelOSD/blob/233e147ba175e0d5cd57e8901535ce0d0372aa6a/doc/OSD.md#osd_cmd_widget_set_config--115-----since-api-2) does not clearly mention that this command return a response. If you dig deeper there is a brief mention [HERE](https://github.com/FrSkyRC/PixelOSD/blob/233e147ba175e0d5cd57e8901535ce0d0372aa6a/doc/WIDGETS.md#widget-configuration) that `OSD_CMD_WIDGET_SET_CONFIG` command can sometimes return an error

> Some widgets have additional restrictions and won't accept any arbitrary configuration. In those cases, OSD_CMD_WIDGET_SET_CONFIG will return an error.

But it isn't stated anywhere that they also return a response when there is no error (from what I can see containing the payload used for configuration).

I believe that should be stated more clearly in the documentation.

**Comment by fiam** [comment]
Thanks for the heads up. It returns the applied configuration, that might be slightly different from the requested one. Although for now no widgets alter the requested configuration, I added that to ease forward compatibility in case we add a widget that needs it in a future version.

**Comment by pawelsky** [comment]
That is fine, but this needs to be clearly documented.
