### ISSUE TITLE
Chargauge widget does not use rect metadata correctly

### ISSUE THREAD

**Issue by pawelsky** [FrSkyRC/PixelOSD#15]
I'm using the following character to display chargauge

![image](https://user-images.githubusercontent.com/7121220/88239580-1861ca00-cc85-11ea-9df2-0aec19032ce5.png)

together with the following metadata

```
metadata:
# Rectangle to fill with battery percentage
- s: r
- u8: 5
- u8: 4
- u8: 3
- u8: 12
# Offset to indicate the direction of the rectangle to full
- s: o
- i8: 0
- i8: -1
# Colors to use the for the filled/unfilled region
- s: c
- c: WHITE, BLACK 
```
This is character 150 from iNav's Vision font.

Log from the simulator confirms the data is stored correctly in the font and read correctly by the simulator.

```
[D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\font.c:68@0] Font storage size 32768K / 8 pages
[D:Z:\Source\FrSky\OSD\firmware\src\main\flash_writer.c:14@23] Flash unlocked, erasing range 03042490-0304a490
erase range 50603152-50635920
[D:Z:\Source\FrSky\OSD\firmware\src\main\osd_output_config.c:39@13503] found osd config at 00000000010F6EB0
[D:Z:\Source\FrSky\OSD\firmware\src\main\osd_output_config.c:39@13506] found osd config at 00000000010F6EB8
set brightness = -1, horizontal offset = 0, vertical offset = 1
listening on serial port COM3
[D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\drawing.c:629@13511] Clear screen
[D:Z:\Source\FrSky\OSD\firmware\src\main\flash_writer.c:53@18369] write finished, flash locked
[D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\drawing.c:629@20477] Clear screen
[D:Z:\Source\FrSky\OSD\firmware\src\main\widgets\sidebar.c:244@20505] sidebar widget 0 configured in rect (10, 50) (75x150)
[D:Z:\Source\FrSky\OSD\firmware\src\main\widgets\sidebar.c:244@20995] sidebar widget 1 configured in rect (275, 50) (75x150)
[D:Z:\Source\FrSky\OSD\firmware\src\main\widgets\graph.c:672@21509] Graph 0 setup from (4, 52) to (176, 196) (172x144)
[D:Z:\Source\FrSky\OSD\firmware\src\main\osd_protocol.c:130@22001] Requesting font character 150
[D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\font.c:126@22004] Read font at addr 150
[D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\font.c:127@22006] 0x55 0x55 0x55 0x55 0x55 0x55 0x55 0x00 0x15
 [D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\font.c:127@22009] 0x54 0xaa 0x85 0x54 0x80 0x85 0x54 0x80
 [D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\font.c:127@22011] 0x85 0x54 0x80 0x85 0x54 0x80 0x85 0x54
 [D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\font.c:127@22015] 0x80 0x85 0x54 0x80 0x85 0x54 0x80 0x85
 [D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\font.c:127@22017] 0x54 0x80 0x85 0x54 0x80 0x85 0x54 0x80
 [D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\font.c:127@22019] 0x85 0x54 0x80 0x85 0x54 0x80 0x85 0x54
 [D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\font.c:127@22022] 0xaa 0x85 0x55 0x00 0x15 0x72 0x05 0x04
 [D:Z:\Source\FrSky\OSD\firmware\src\main\drawing\font.c:127@22024] 0x03 0x0c 0x6f 0x00 0xff 0x63 0x02
```

Unfortunately the gauge does not match the character (looks like it is 2 instead of 3 pixels wide).

![image](https://user-images.githubusercontent.com/7121220/88239870-ddac6180-cc85-11ea-8bb0-d9c142051437.png)

in addition to that when the gauge is erased and then drawn again only the gauge part is displayed, without the character itself

![image](https://user-images.githubusercontent.com/7121220/88239933-07658880-cc86-11ea-998c-e7e00bcb357f.png)

I'm using windows simulator v1.0.1

On the OSD the gauge does not even configure and returns error -5 even though the same code is used as on simulator.

**Comment by fiam** [comment]
I've fixed this in our internal repo (so the issue will close itself automatically once I push it). I'm gonna fix a couple of small bugs and then I'll prepare a new release of the simulator and the firmware.

**Comment by pawelsky** [comment]
Great, waiting for the releases then!

**Comment by fiam** [comment]
@pawelsky I've pushed simulator 1.0.2 a few minutes ago. Please, give it a try when you have time. Thanks!

**Comment by pawelsky** [comment]
The widgets seem to erase themselves correctly, and the chargauge bar is matching the metadata now.

Unfortunately the problem with missing character after the chargauge is erased is still there

![image](https://user-images.githubusercontent.com/7121220/90320747-07367100-df44-11ea-9788-32da5f5eb46f.png)

**Comment by fiam** [comment]
Thanks a lot for testing it. I totally missed that part of the bug <facepalm>. I'll prepare a v1.0.3 tomorrow.

**Comment by fiam** [comment]
Bug should be fixed in this build. I changed the widget to probe the canvas instead of caching the values in its state, so now it should be able to figure out when it needs a full redraw correctly. Please, let me know if works fine for you. Thanks!

[FrSkyOSD-simulator-v1.0.3-alpha.0-win64.zip](https://github.com/FrSkyRC/PixelOSD/files/5079549/FrSkyOSD-simulator-v1.0.3-alpha.0-win64.zip)

**Comment by pawelsky** [comment]
Yes, the chargauge widget seems to be redrawing itself fine in v1.0.3 alpha.

**Comment by fiam** [comment]
Thanks for testing it. I'll put together another release later today.

**Comment by pawelsky** [comment]
>  I'm gonna fix a couple of small bugs and then I'll prepare a new release of the simulator and the firmware.

Probably it would be good to look into https://github.com/FrSkyRC/PixelOSD/issues/17 before release

**Comment by pawelsky** [comment]
@fiam Any news about the new firmware release? :)

**Comment by pawelsky** [comment]
Tested with the [beta firmware 2.0.1](https://github.com/FrSkyRC/PixelOSD/issues/17#issuecomment-711032530) - and it solves the issue
