### ISSUE TITLE
Firmware upgrade/downgrade messes up the font

### ISSUE THREAD

**Issue by pawelsky** [FrSkyRC/PixelOSD#16]
When you upgrade the OSD firmware from version 1.0.0 to version 2.0.0 the font gets messed up and needs to be reuploaded.

Here is the font display during the upgrade process
![image](https://user-images.githubusercontent.com/7121220/88345837-3132b400-cd47-11ea-9d4c-cd6bdf8fab7f.png)

Here if is after the upgrade finished and the OSD has been disconnected and then connected again
![image](https://user-images.githubusercontent.com/7121220/88345882-490a3800-cd47-11ea-9af5-7cceed0170cd.png)

You can observe similar behaviour when downgrading from 2.0.0 to 1.0.0

Not sure if that is expected due to changes in the firmware or a bug, but it should be at least mentioned in the release notes (note that font is not re-read just after the upgrade, so people may not notice that and then get strange results on screen).

**Comment by fiam** [comment]
Thanks for the heads up! I've added a note in the docs and I'll push the changes later today.
