### ISSUE TITLE
OSD Flickers at top of loop

### ISSUE THREAD

**Issue by jmxp69** [FrSkyRC/PixelOSD#19]
Video shows the issue. F722-WPX with inav 2.6 and OSD Firmware 2.0.0 flashed with app.

https://youtu.be/8bE8jnJfdmg

**Comment by expipiplus1** [comment]
This is because the decimal part of the value is being rendered without proper zero.

**Comment by alberto-frsky** [comment]
@jmxp69 Thanks for providing a video of the problem. This looks like a problem with your wiring, doesn't it? Only thing that could affect the video signal depending on the physical orientation of the aircraft would be a bad joint that causes a poor contact when the plane is upside down. Maybe you have something pulling the camera/OSD/VTX wires?

**Comment by pawelsky** [comment]
I don't think the issue was about video, vide looks fine, from what I see on the movie it is just the OSD that flickers when the video is very bright. Looks similar to https://github.com/FrSkyRC/PixelOSD/issues/18

**Comment by jmxp69** [comment]
It's not the wiring. This isn't my first rodeo wiring a VTX. It could be an SMD flexing on the board, but it's not my wiring, and this is repeatable.
