### ISSUE TITLE
OSD symbol lines not drawn in sync

### ISSUE THREAD

**Issue by Jetrell** [FrSkyRC/PixelOSD#20]
The images describe the problem more that words can. 
From them its easy to see how the sharpness of the pixel OSD characters is very poor, in comparison to the 7456 characters.

I have attempted too clean them up using Brightness on the App, with no effect.

The image here is taken from a screen shot of the DVR footage. While in reality, the characters are extremely poor in appearance when viewed through OLED goggles. Many characters are impossible to read at a glance.

Pixel OSD
![Pixel OSD](https://user-images.githubusercontent.com/47995726/107309185-1145c080-6ade-11eb-8b2d-a4b11ed8cb88.JPG)
Character OSD
![7456](https://user-images.githubusercontent.com/47995726/107309198-199dfb80-6ade-11eb-87e5-fc3c3d9ac871.JPG)

Pixel OSD
![Pixel OSD 2](https://user-images.githubusercontent.com/47995726/107309206-1e62af80-6ade-11eb-8177-c9e63f79230e.JPG)
Character OSD
![7456 2](https://user-images.githubusercontent.com/47995726/107309212-202c7300-6ade-11eb-8416-2d0730ab8d34.JPG)

Pixel OSD
![Pixel OSD 3](https://user-images.githubusercontent.com/47995726/107309218-23276380-6ade-11eb-9955-f2409ac04ab2.JPG)
Character OSD
![7456 3](https://user-images.githubusercontent.com/47995726/107309224-26225400-6ade-11eb-9c74-bb88af14cba0.JPG)

These images were taken on an F722-WPX and an Frsky pixel OSD breakout board.
I have noticed the same effect on many Frsky pixel OSD reviews on YouTube as well. Although the YT compression masks the problem a bit.

Without meaning to sound disrespectful of the time and effort put into coding this. I have chosen to return to character OSD flight controllers, while flying analog, until this issue can be fixed.

**Comment by alberto-frsky** [comment]
Hi @Jetrell,

Thanks for your suggestion. Unfortunately, this is a limitation of the current iteration of the hardware. I did search and test a lot of fast switches, but for the packages and on resistance that we needed, that's the best I response I could find, which looked acceptable to me. We have plans to continue iterating on the OSD with both better hardware and software, but I can't give you an accurate timeline.

If you found that problem to be a dealbreaker for your use case, I think returning to a character based OSD is the best course of action. No offence taken :-)

**Comment by Jetrell** [comment]
@alberto-frsky Thank you for your time and the response. I will keep an eye open for the next iteration.
