### ISSUE TITLE
Connect SIM to Serial Port 

### ISSUE THREAD

**Issue by jnmill** [FrSkyRC/PixelOSD#21]
How do I configure the SIM to listen to the Serial Port.  My device is on COMM port 4, I would like to switch from the TCP port to the virtual serial port. 
thanks

**Comment by fiam** [comment]
@jnmill You can make the simulator read/write from a serial port with the `-serial-port` command line argument. e.g. for COM4 you can launch it with `-serial-port COM4`. Please, see the `-help` flag which lists all the available options.

**Comment by jnmill** [comment]
Got it used --serial-port com4
Thanks Alberto

**Comment by fiam** [comment]
I'm glad you got it working 👍
