### ISSUE TITLE
With Imperial units selected the OSD label changes to MPH, but numbers and ladder appears to still be in KMH

### ISSUE THREAD

**Issue by ShawnzAZ** [FrSkyRC/PixelOSD#3]
With Imperial units selected the OSD label changes to MPH, but numbers and ladder appears to still be in KMH.  The status screen at the end of the flight seems to shows the max speed correctly even through the speed ladder read higher during the flight.

Matek F722-px with FrSkt OSD 2.0.1 flashed / inav 2.6 from Matek site,

**Comment by ShawnzAZ** [comment]
![image](https://user-images.githubusercontent.com/30354308/85961840-f6b14380-b961-11ea-9ad8-2391239109a6.png)
in flight...

**Comment by ShawnzAZ** [comment]
upon landing..
![image](https://user-images.githubusercontent.com/30354308/85961860-16486c00-b962-11ea-8d53-6b88874db8f1.png)

**Comment by ShawnzAZ** [comment]
Definitely something off with the scaling of the ladder:

![image](https://user-images.githubusercontent.com/30354308/86638625-79528800-bf8c-11ea-857c-215fb374adbf.png)

**Comment by fiam** [comment]
@ShawnzAZ Thanks for the detailed report. It seems to be a bug in the INAV side, but let's track it here anyway since it's in the code I wrote for the PixelOSD driver.
