### ISSUE TITLE
Simulator incorrectly interpreting osd_point_t and osd_size_t structures

### ISSUE THREAD

**Issue by pawelsky** [FrSkyRC/PixelOSD#4]
Looks like the simulator expects the x, y, width, height values to be 16 bit rather than 12 bit as in the documentation.

When I define the osd_point_t and osd_size_t as
```
typedef struct __attribute__((packed))
{
  int16_t x : 12;
  int16_t y : 12;
} osd_point_t;
typedef struct __attribute__((packed))
{
  int16_t width : 12;
  int16_t height : 12;
} osd_size_t;

```
the simulator rejects the commands using it with an error
_[W:Z:\Source\FrSky\OSD\firmware\src\common\osd_protocol_async.c:180@42745] error -3 in response to cmd XX_

When I define them as
```
typedef struct __attribute__((packed))
{
  int16_t x;
  int16_t y;
} osd_point_t;
 typedef struct __attribute__((packed))
{
  int16_t width;
  int16_t height;
} osd_size_t;

```
the simulator works fine.

I'm using simulator v1.0.0

**Comment by fiam** [comment]
Hi @pawelsky. This seems to be a Windows specific bug, I'm looking into it.

**Comment by pawelsky** [comment]
Oh, forgot to mention that in the description, but indeed I was using windows. I can test the mac version as well if it helps.

**Comment by fiam** [comment]
@pawelsky I noticed you were running the Windows version by the file path in the log message. Don't waste your time testing on macOS, I've already tested it in macOS, Linux and Windows and it only fails in the latter. I will post a new build as soon as I fix it.

**Comment by fiam** [comment]
@pawelsky I've tested the fixes against the Python SDK and it works fine for me. Just to make sure, could you give a try to this binary? Thanks!
[FrSkyOSD-simulator-v1.0.1-win64.zip](https://github.com/FrSkyRC/PixelOSD/files/4924500/FrSkyOSD-simulator-v1.0.1-win64.zip)

**Comment by pawelsky** [comment]
@fiam  Yes, I can confirm it is now working on my end as well

![image](https://user-images.githubusercontent.com/7121220/87540428-fd4cf400-c69f-11ea-9689-babe85743810.png)

**Comment by fiam** [comment]
Thanks for the confirmation!
