### ISSUE TITLE
Wrong type of angle argument of OSD_CMD_CTM_U16_ROTATE_REV command

### ISSUE THREAD

**Issue by pawelsky** [FrSkyRC/PixelOSD#5]
In the documentation the type of the OSD_CMD_CTM_U16_ROTATE_REV command angle arbument is specified as float32 while (as the cmd name itself suggests) it should be uint16_t.

See https://github.com/FrSkyRC/PixelOSD/blob/4e153c6c66173283ca74a3ebbb081acc1fd4cd83/doc/OSD.md#osd_cmd_ctm_u16_rotate_rev--99-----since-api-2

Also a minor issue - for consistency with other commands the name of the command should probably be _OSD_CMD_CTM_U16ROTATE_REV_ not _OSD_CMD_CTM_U16_ROTATE_REV_ (no dash between U16 and ROTATE)

**Comment by fiam** [comment]
Hi @pawelsk, thanks for the heads up! The command is indeed incorrectly documented, the code does expect an uint16_t. I'm gonna push a fix right now and also rename it following your suggestion.

**Comment by pawelsky** [comment]
Great! Thanks for a quick reply!

**Comment by fiam** [comment]
My pleasure! OT: Thanks for your NAZA decoder library, it's what got me interested in electronics and hardware design many years ago!
