### ISSUE TITLE
[SIMULATOR] [MINOR] Increasing the display scale with "+" in simulator has no effect

### ISSUE THREAD

**Issue by pawelsky** [FrSkyRC/PixelOSD#6]
Pressing "+" to increase the display scale in simulator has no effect. Changing scale with "1", "2", "3" and "-" works as expected.

Tested on Windows version 1.0.1 and macOS version 1.0.0. Did not test the Linux version.

**Comment by fiam** [comment]
I've just tested it in macOS and it seems to work on my laptop keyboard. Are you testing with the key in the numeric keypad or  the `+` in the "main" keyboard? Re-reading the code, I suspect I'm not handling keypresses from the numeric keypad correctly, but I don't have any keyboards with numeric keypad here to test right now.

**Comment by pawelsky** [comment]
No, I'm using the +/= key next to backspace (on the numeric keypad neither - nor + work). I've tested both English US and POL Programmers keyboard settings. I'm guessing you are located in Spain and probably use the Spanish keyboard so I've switched to Spanish ISO keyboard and then it works but with "]" key for + and "/" key for -.

I guess this needs to be somehow made input language independent.

**Comment by fiam** [comment]
I'm handling keyboard input via SDL2. The problem is that SDL2 doesn't seem to map `+` consistently between keyboard layouts, unlike the rest of keys the simulator uses for input. I've tested it with multiple layouts, including US and POL, and I've added a workaround that should fix the problem.

**Comment by pawelsky** [comment]
Confirmed fixed on Simulator v1.0.2 (Windows version)

**Comment by fiam** [comment]
Thanks for testing it, much appreciated!
