### ISSUE TITLE
[DOCUMENTATION] [QUESTION] How to distinguish between OSD_CMD_GET_SETTINGS and OSD_CMD_SET_SETTINGS commands?

### ISSUE THREAD

**Issue by pawelsky** [FrSkyRC/PixelOSD#7]
In the documentation both OSD_CMD_GET_SETTINGS and OSD_CMD_SET_SETTINGS commands have the same ID 9. I'm assuming that the way the OSD and the simulator distinguish the two requests is by the payload size. The OSD_CMD_GET_SETTINGS command seems to be working fine, it returns the current settings, however when I issue a OSD_CMD_SET_SETTINGS command with the following payload:
```
settings_version = 2
brightness = -1
horizontal_offset = 0
vertical_offset = 1
```
I'm getting the following error:
_[W:Z:\Source\FrSky\OSD\firmware\src\main\osd_protocol.c:1069@5366] unknown command 255
[W:Z:\Source\FrSky\OSD\firmware\src\common\osd_protocol_async.c:180@5369] error -2 in response to cmd 255_

That would suggest that the -1 value for brightness rather than being interpreted as a continuation OSD_CMD_SET_SETTINGS payload is treated as a next command (int -1 = uint 255).

Am I reading the documentation wrong, is it a mistake in OSD_CMD_SET_SETTINGS ID or a bug in the OSD firmware/simulator?

I'm using Windows simulator v1.0.1 but also have the same problem with OSD firmware v2.0.0

P.S. OSD_CMD_SAVE_SETTINGS command works as expected.

**Comment by fiam** [comment]
Thanks for heads up. The documentation is incorrect, I'll update it right now. `OSD_CMD_SET_SETTINGS` is `10` and `OSD_CMD_SAVE_SETTINGS` is `11`.
